# -*- coding: utf-8 -*-
"""CircuitPython Three-Joint Teleoperation Control

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TQVn4aHoTxc-xuCtQYlDJnbE5qwDRSUK
"""

# CircuitPython Code for Robot Arm Three-Joint Teleoperation Control
# Controls three servo joints (J1, J2: MG996R; J3: SG90) using three potentiometers.
#
# TARGET BOARD: Adafruit Feather RP2040
# This code requires the following libraries (to be placed in your 'lib' folder):
# - adafruit_motor
# - adafruit_bus_device
#
# WIRING (Feather RP2040 Pinout):
# ----------------------------------------------------
# POTENTIOMETER 1 (J1 Control) Signal 	-> board.A1 (GPIO 27) (Analog)
# POTENTIOMETER 2 (J2 Control) Signal 	-> board.A0 (GPIO 26) (Analog)
# POTENTIOMETER 3 (J3 Control) Signal 	-> board.A3 (GPIO 29) (Analog)
#
# SERVO 1 (J1 Actuator, MG996R) Signal 	-> board.D5 (GPIO 6) <--- NEW, SAFE DIGITAL PIN
# SERVO 2 (J2 Actuator, MG996R) Signal 	-> board.D6 (GPIO 7) <--- NEW, SAFE DIGITAL PIN
# SERVO 3 (J3 Actuator, SG90) Signal 	-> board.D9 (GPIO 4) <--- NEW, SAFE DIGITAL PIN
#
# SHARED VCC/GND -> Dedicated External 5V Power Supply/GND (CRITICAL FOR MG996R)

import board
import time
import pwmio
import analogio
from adafruit_motor import servo
from simpleio import map_range

# ---------------------------
# --- HARDWARE DEFINITIONS ---
# ---------------------------

# Pin Definitions
POT_J1_PIN = board.A1 		    # Pot for Joint 1 (Base/Shoulder)
POT_J2_PIN = board.A0 		    # Pot for Joint 2 (Elbow)
POT_J3_PIN = board.A3 		    # Pot for Joint 3 (Wrist/Gripper)

# *** UPDATED SERVO PINS ***
SERVO_J1_PIN = board.D5 		# Joint 1 MG996R
SERVO_J2_PIN = board.D6 		# Joint 2 MG996R
SERVO_J3_PIN = board.D9 		# Joint 3 SG90

PWM_FREQ = 50 	                # Standard servo frequency (50Hz)

# Servo Pulse Widths
# MG996R (J1 & J2)
MG996R_MIN_PULSE = 400
MG996R_MAX_PULSE = 2600
# SG90 (J3)
SG90_MIN_PULSE = 500
SG90_MAX_PULSE = 2500

# --- CRITICAL CALIBRATION VALUES (Assumed equal for all pots) ---
POT_MIN_RAW = 88
POT_MAX_RAW = 65200

# ---------------------------
# --- MAIN INITIALIZATION ---
# ---------------------------

# 1. Initialize PWM and Servos
try:
    # Joint 1 Servo (MG996R)
    pwm_j1 = pwmio.PWMOut(SERVO_J1_PIN, duty_cycle=2 ** 15, frequency=PWM_FREQ)
    my_servo_j1 = servo.Servo(pwm_j1, min_pulse=MG996R_MIN_PULSE, max_pulse=MG996R_MAX_PULSE)

    # Joint 2 Servo (MG996R)
    pwm_j2 = pwmio.PWMOut(SERVO_J2_PIN, duty_cycle=2 ** 15, frequency=PWM_FREQ)
    my_servo_j2 = servo.Servo(pwm_j2, min_pulse=MG996R_MIN_PULSE, max_pulse=MG996R_MAX_PULSE)

    # Joint 3 Servo (SG90) - Uses specific pulse widths
    pwm_j3 = pwmio.PWMOut(SERVO_J3_PIN, duty_cycle=2 ** 15, frequency=PWM_FREQ)
    my_servo_j3 = servo.Servo(pwm_j3, min_pulse=SG90_MIN_PULSE, max_pulse=SG90_MAX_PULSE)


    # CRITICAL SAFETY STEP: Set all servos to a safe, central position (90 degrees)
    my_servo_j1.angle = 90
    my_servo_j2.angle = 90
    my_servo_j3.angle = 90
except Exception as e:
    print(f"Error initializing Servos: {e}")
    raise e

# 2. Initialize Analog Input (Potentiometers)
try:
    pot_j1 = analogio.AnalogIn(POT_J1_PIN)
    pot_j2 = analogio.AnalogIn(POT_J2_PIN)
    pot_j3 = analogio.AnalogIn(POT_J3_PIN)
except Exception as e:
    print(f"Error initializing AnalogIn: {e}")
    raise e

print("Robot Arm 3-DOF Control Initialized. Ready for teleoperation.")


# ---------------------------
# --- MAIN CONTROL LOOP ---
# ---------------------------

while True:

    # --- Joint 1 Control (MG996R) ---
    raw_value_j1 = pot_j1.value
    angle_j1 = map_range(raw_value_j1, POT_MIN_RAW, POT_MAX_RAW, 0, 180)
    angle_j1 = max(0, min(180, angle_j1))
    my_servo_j1.angle = int(round(angle_j1))

    # --- Joint 2 Control (MG996R) ---
    raw_value_j2 = pot_j2.value
    angle_j2 = map_range(raw_value_j2, POT_MIN_RAW, POT_MAX_RAW, 0, 180)
    angle_j2 = max(0, min(180, angle_j2))
    my_servo_j2.angle = int(round(angle_j2))

    # --- Joint 3 Control (SG90) ---
    raw_value_j3 = pot_j3.value
    angle_j3 = map_range(raw_value_j3, POT_MIN_RAW, POT_MAX_RAW, 0, 180)
    angle_j3 = max(0, min(180, angle_j3))
    my_servo_j3.angle = int(round(angle_j3))

    # NO DELAY: Loop runs as fast as possible for responsiveness.